version: '2'

services:
  docker-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=docmanagesys
      - MYSQL_PASSWORD=123456
    ports:
      - 3306:3306

  docker-docsys:
    build:
      context: .
    depends_on:
      - docker-mysql
    ports:
      - 9090:9090
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=docmanagesys
      - DATABASE_PORT=3306
    volumes:
      - /root/spring_boot/file_storage:/file_storage
