INSERT IGNORE INTO roles(name) VALUES('ROLE_USER');
INSERT IGNORE INTO roles(name) VALUES('ROLE_ADMIN');

INSERT IGNORE INTO file_types(name) VALUES('FILE_TYPE_TXT');
INSERT IGNORE INTO file_types(name) VALUES('FILE_TYPE_DOC');
INSERT IGNORE INTO file_types(name) VALUES('FILE_TYPE_PPT');
INSERT IGNORE INTO file_types(name) VALUES('FILE_TYPE_XLS');
INSERT IGNORE INTO file_types(name) VALUES('FILE_TYPE_PDF');
INSERT IGNORE INTO file_types(name) VALUES('FILE_TYPE_OTHER');
