spring:
  datasource:
    url: jdbc:mysql://docker-mysql:3306/docmanagesys?useSSL=false&serverTimezone=GMT%2B8&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: GMT+8
  security:
    user:
      name: houlx
      password: 123
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000

server:
  port: 9090
