spring:
  datasource:
    url: jdbc:mysql://localhost:3306/docmanagesys?useSSL=false&serverTimezone=GMT%2B8&useLegacyDatetimeCode=false #TODO the mysql url need to be changed when deploying
    username: root
    password: 123456
    initialization-mode: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: GMT+8
  security:
    user:
      name: houlx
      password: 123
  servlet:
    multipart:
      max-file-size: 20MB

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
  save_file_path: /Users/houlx/Important/GraduationProject/FileStorage/ #TODO this need to be changed to path in ubuntu server
  resource-handler: /resource/**
  #preview-path: /root/demo/ #TODO this need to be ensure the preview path of ubuntu server
  #preview-server: http://39.96.211.100:8012/demo/ #TODO this need to be ensure the preview server 8012 of ubuntu server

server:
  port: 9090
