spring:
  datasource:
    url: jdbc:mysql://localhost:3306/docmanagesys?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 123456
    initialization-mode: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  security:
    user:
      name: houlx
      password: 123

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
